language: bash
services: docker
sudo: required

env:
  - IMAGE: tdmproject/tiledb

install:
  - docker build -t $IMAGE -f docker/Dockerfile docker/

script:
  - docker-compose up -d
  - docker exec datanode bash -c 'until datanode_cid; do sleep 0.1; done'
  - docker cp .travis/quickstart_dense.py tiledb:/
  - docker exec tiledb bash -l -c "python3 quickstart_dense.py"
  - docker exec namenode hdfs dfs -ls /quickstart_dense


deploy:
  - provider: script
    script: bash .travis/push.sh
    on:
      repo: crs4/tiledb-docker
      branch: master
