version: "3"

services:

  namenode:
    image: crs4/namenode:3.2.0
    container_name: namenode
    ports:
      - "8020:8020"
      - "9870:9870"
      - "9871:9871"

  datanode:
    image: crs4/datanode:3.2.0
    container_name: datanode
    ports:
      - "9864:9864"
      - "9865:9865"
      - "9866:9866"
      - "9867:9867"
    environment:
      - NAMENODE_HOSTNAME=namenode

  client:
    image: crs4/tiledb
    container_name: tiledb
    environment:
      - NAMENODE_HOSTNAME=namenode
